import 'package:flutter/material.dart';

const colorWhite = Colors.white;
const colorBlue = Colors.blue;
const colorBlack = Colors.black;
const colorGrey = Colors.grey;
const colorMineShaft = Color(0xff363636);
const colorAmber = Colors.amber;
const colorParisDaisy = Color(0xffFFEB61);
const colorWildSand = Color(0xffF4F4F4);
const colorDairyCream = Color(0xffF8F0B9);
const colorDawnPink = Color(0xffEBEBEB);
const colorOrange = Color.fromARGB(255, 233, 142, 14);
const colorGreen = Color.fromARGB(255, 14, 233, 58);
const colorMobyDick = Color(0xffDEE8EE);
const colorBackground = Color(0xffFDFDFF);
const colorWildSand2 = Color(0xffF5F5F5);
const colorCodGrey = Color(0xff1D1D1D);
const colorPeach = Color(0xffFFE8B4);
const colorDarkGreen = Color(0xff075e54);
const colorLightDarkGreen = Color(0xff128c7e);
const colorLightGreen = Color(0xff25d366);
